import type { Metadata } from "next"

const SITE_NAME = "Aether Practice"
/** Brand-first title pattern applied by both root layouts; pages pass only the topic. */
export const TITLE_TEMPLATE = `${SITE_NAME} | %s`
const BASE_URL = "https://aetherpractice.com"
export const OG_IMAGE_ALT = "Aether Practice — Cognitive wellbeing and online counseling"

/**
 * Builds a page's Metadata: title, description, canonical URL, and matching
 * Open Graph + Twitter card tags so link previews (WhatsApp, iMessage,
 * LinkedIn, Facebook, X) show the right title and summary for each page.
 *
 * The shared social preview image is generated by app/opengraph-image.tsx.
 * It has to be referenced explicitly here because a per-page openGraph object
 * replaces (rather than merges with) the root one, which would otherwise drop
 * the inherited image.
 */
export function pageMetadata({
  title,
  description,
  path,
  locale = "en_US",
  languages,
  type = "website",
  publishedTime,
  modifiedTime,
  section,
  tags,
  image,
}: {
  /** The page topic only, e.g. "Couples Therapy Online". The root layout prefixes the brand. */
  title: string
  description: string
  /** Path starting with "/", e.g. "/about". */
  path: string
  /** Open Graph locale, e.g. "en_US" or "nb_NO". */
  locale?: string
  /**
   * hreflang alternates, e.g. { en: "/", no: "/online-therapy-norway" }.
   * Paths starting with "/" are resolved against BASE_URL. Only set this on
   * pages that have a real alternate-language counterpart elsewhere on the
   * site — it must be reciprocated on that other page or Google ignores it.
   */
  languages?: Record<string, string>
  type?: "website" | "article"
  publishedTime?: string
  modifiedTime?: string
  section?: string
  tags?: string[]
  /** Page-specific social image path, e.g. a post's hero image. Falls back to the shared site image. */
  image?: string
}): Metadata {
  const url = `${BASE_URL}${path}`
  const fullTitle = TITLE_TEMPLATE.replace("%s", title)
  const socialImage = image
    ? { url: image, alt: title }
    : { url: "/opengraph-image", width: 1200, height: 630, alt: OG_IMAGE_ALT }

  return {
    title,
    description,
    alternates: {
      canonical: url,
      ...(languages && {
        languages: Object.fromEntries(
          Object.entries(languages).map(([lang, href]) => [
            lang,
            href.startsWith("/") ? `${BASE_URL}${href}` : href,
          ]),
        ),
      }),
    },
    openGraph: {
      type,
      siteName: SITE_NAME,
      locale,
      url,
      title: fullTitle,
      description,
      images: [socialImage],
      ...(type === "article" && {
        publishedTime,
        modifiedTime,
        section,
        tags,
      }),
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [{ url: socialImage.url, alt: socialImage.alt }],
    },
  }
}

/**
 * Service JSON-LD tying a service page to the root Organization (via @id) so
 * AI/search systems can resolve "who provides this" without re-declaring the
 * organization on every page.
 */
export function serviceJsonLd({
  name,
  description,
  path,
  areaServed,
  serviceType,
  inLanguage = "en",
}: {
  name: string
  description: string
  /** Path starting with "/", e.g. "/couples-therapy". */
  path: string
  areaServed: string[]
  /** Category of service, e.g. "Couples therapy". Defaults to the name. */
  serviceType?: string
  /** BCP 47 language of the page, "en" or "nb". */
  inLanguage?: "en" | "nb"
}) {
  const url = `${BASE_URL}${path}`
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name,
    serviceType: serviceType ?? name,
    description,
    url,
    inLanguage,
    provider: { "@id": `${BASE_URL}/#organization` },
    areaServed: areaServed.map((place) => ({ "@type": "AdministrativeArea", name: place })),
    // Sessions are delivered online only.
    availableChannel: {
      "@type": "ServiceChannel",
      name: inLanguage === "nb" ? "Videosamtale" : "Online video session",
      serviceUrl: url,
      availableLanguage: inLanguage === "nb" ? ["nb", "en"] : ["en", "nb"],
    },
  }
}

/** BreadcrumbList JSON-LD. First item should usually be Home. */
export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: item.path.startsWith("http") ? item.path : `${BASE_URL}${item.path}`,
    })),
  }
}
